### ISSUE TITLE
Docker-Mailserver v2.1

### ISSUE THREAD

**Issue by tomav** [tomav/docker-mailserver#257]
This is non exhaustive list of what can be done in `docker-mailserver 2.1`. Let me know if you have ideas.
**I'm also looking for contributors (#236)**

### New features
- [ ] Easy config for secondary / backup MX server (#254)

### Bug fixes
- [ ] Fix bug in selective services (#256)

### Refactor
- [ ] Refactor `ENV` enable/disable. "Everything" should be disabled by default to let users configure their container (#297)
- [ ] Dive deep into TravisCI matrix build to run faster builds / or have more maintainable test suite

### Documentation
- [ ] Improve SASL documentation

**Comment by Zehir** [comment]
Maybe you can improve the doc about the sasl auth

**Comment by tomav** [comment]
Hi @Zehir, yeah probably. I personally don't use it so I'm not an expert.
I'm currently refactoring tests and when I look at SASL, they're not clear neither.

Do you have any input based on your experience? Feel free to update the Wiki if you have useful informations.

I log your request in 2.1.

**Comment by Zehir** [comment]
I have no experience about SASL, I try to use it but the doc what I have found is not clear. Some say that the auth is "AUTH PLAIN "+ base 64 of username\0username\0password or username\@host\0password but none work.

**Comment by tomav** [comment]
I used it in the `docker-mailserver v1`, we can see in the tests.
I think I used [this page](http://www.samlogic.net/articles/smtp-commands-reference-auth.htm) as doc.

**Comment by Zehir** [comment]
In the docker compose doc https://docs.docker.com/compose/networking/#/networking-in-compose
He says that when you create a container with docker-compose a bridge named mail_default is created
With the command docker network inspect mail_default I see this network:

```json
[
    {
        "Name": "mail_default",
        "Id": "LONG_STRING",
        "Scope": "local",
        "Driver": "bridge",
        "EnableIPv6": false,
        "IPAM": {
            "Driver": "default",
            "Options": null,
            "Config": [
                {
                    "Subnet": "172.18.0.0/16",
                    "Gateway": "172.18.0.1/16"
                }
            ]
        },
        "Internal": false,
        "Containers": {},
        "Options": {},
        "Labels": {}
    }
]
```
Maybe in the install script you should detect network address for [mynetworks](https://github.com/tomav/docker-mailserver/blob/master/target/postfix/main.cf#L14) options.

**Comment by tomav** [comment]
Yes, that's what I suggested in the other thread.
I create another issue separated from this roadmap.

**Comment by Zehir** [comment]
You can also upgrade to ubuntu lts 16.04

**Comment by traedamatic** [comment]
Hello, 
first of all I want to thank you for this great project. I use this docker container for my mailserver and it works great. 
But I have one question, is their any idea about improving the spam filter. I think about a automatically update for the spam databases for spamav. 
On my last server I had a cron task that searched through a IMAP folder that contained all the spam messages. Because of that I could manually mark a message as spam.  Do you have anything in plan?

**Comment by tomav** [comment]
Hi @traedamatic, you're right, it could be added.
Personally, I added a cron on my host machine that triggers `sa-learn` of some specific mailboxes (not all). You can open an issue on that specific point let's see different suggestions on that specific point.

I'm not sure there's a "on size fits all" configuration on that but a single command line explained in the wiki may be useful.

**Comment by Josef-Friedrich** [comment]
see #203

**Comment by Josef-Friedrich** [comment]
@tomav Can you please share your cron entry? Is this topic already in the wiki?

**Comment by tomav** [comment]
`0 2 * * 1 docker exec mail sa-learn --spam /var/mail/domain.com/username/.Junk`

I'll add it to Wiki in the next minutes.

**Comment by tomav** [comment]
https://github.com/tomav/docker-mailserver/wiki/FAQ-and-Tips#how-can-i-make-spamassassin-learn-spam

**Comment by traedamatic** [comment]
Fast and great. Very nice.

**Comment by tomav** [comment]
Topic postponed, no time/contributors to correctly plan a roadmap.
